### ISSUE TITLE
你好，这个安装在centos7中，是不是对环境有要求啊

### ISSUE THREAD

**Issue by hongjia88** [erisesoft/erisesoft.github.io#2]
Finding MySQL UDF plugin directory ...这个进行不下去，安装啦mysql5.7.2能过去啦
之后
# /usr/bin/erisemaild start
/usr/bin/erisemaild: error while loading shared libraries: libmemcached.so.11: cannot open shared object file: No such file or directory
安装libmemcached也不行，请把环境要求说明一下，谢谢。

**Comment by uplusware** [comment]
您好， 估计您安装错 libmemecached 版本了。

**Comment by erisesoft** [comment]
您好，您可以下载CentOS版安装。

[CentOS7 简体中文版](https://github.com/uplusware/erisemail/raw/master/centos7-erisemail-bin-cn-utf8-x86_64-linux-1.6.10.tar.gz)

[CentOS7 English Version](https://github.com/uplusware/erisemail/raw/master/centos7-erisemail-bin-en-utf8-x86_64-linux-1.6.10.tar.gz)

[CentOS7 分布式简体中文版](https://github.com/uplusware/erisemail/raw/master/centos7-erisemail-bin-cn-utf8-x86_64-linux-1.6.10-dist.tar.gz)

[CentOS7 Distributed English Version](https://github.com/uplusware/erisemail/raw/master/centos7-erisemail-bin-en-utf8-x86_64-linux-1.6.10-dist.tar.gz)
